### ISSUE TITLE
Add Agent/Person error via UI: namespace must not be blank

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-ui#1123]
Choosing ORCID from drop-down for a Person and populating the value results in error thrown when saving the record. Looks like the values for the namespace in the drop-down are not sticking and/or the identifier resource does not get created concurrent with creation of the Person record.
<img width="482" alt="Screen Shot 2023-09-07 at 2 23 23 PM" src="https://github.com/AAFC-BICoE/dina-ui/assets/326459/af6c55ee-3c68-42a6-97dc-65196270bd16">

**Comment by cgendreau** [comment]
Done
