### ISSUE TITLE
Draw the EN and FR descriptions on managed attributes into tooltips on views

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-ui#1339]
As in the subject. These are shown on data ingestion, which is great but not (consistently?) shown on view. An example where a tooltip would be useful on view is the OCR managed attribute on an item in the object store to forewarn the uninitiated how the content was produced and on its lack of dependability.

**Comment by cgendreau** [comment]
Fixed in 0.162
